apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        image: 746851085552.dkr.ecr.us-east-1.amazonaws.com/clo835-myapp:myapp
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: mysql
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
        - name: DATABASE
          value: employees
