apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 746851085552.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
